name: TheStainedGlassDisplayCompany
favicon: null
layout_spectrum: 0.74924
typography_spectrum: 0.65485
title: All the good stuff on displaying Stained Glass
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#050503'
    - '#583a1d'
    - '#c09f48'
    - '#f4e575'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
