name: TheStainedGlassDisplayCompany
favicon: null
layout_spectrum: 1
typography_spectrum: 0.65485
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#050503'
    - '#583a1d'
    - '#c09f48'
    - '#f4e575'
  brandStrength: 0.6875
  lightness: 0.677109976997599
  saturation: 0.30511707137338817
  rhythmicContrast: 0.11555670527741313
purpose: []
